# Generated by Django 3.1.4 on 2021-01-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Poster',
            field=models.ImageField(blank=True, upload_to='posts'),
        ),
    ]
