# Generated by Django 3.1.4 on 2021-01-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieblog', '0002_post_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Poster',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
