# Generated by Django 3.1.4 on 2021-01-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=85, unique=True)),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
    ]
