# Generated by Django 3.1.4 on 2021-01-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rec', '0001_initial'),
        ('actor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(to='rec.Movie'),
        ),
    ]
